force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Version__c.field-meta.xml
<CustomField>
    <fullName>Document_Version__c</fullName>
    <label>Document Version</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DocumentManagementControllerTest.cls
@IsTest
private class DocumentManagementControllerTest {

    @TestSetup
    private static void testDataSetup(){
        List<Document__c> documentList = new List<Document__c>();

        documentList.add(new Document__c(
            Name = 'Doc 1',
            Document_Category__c = 'Finance',
            Document_Version__c = 2
        ));

        documentList.add(new Document__c(
            Name = 'Doc 2',
            Document_Category__c = 'Interview',
            Document_Version__c = 1
        ));

        INSERT documentList;
    }

    @IsTest
    private static void testGetAllDocument(){
        List<Document__c> documentList = DocumentManagementController.getAllDocuments('', 'CreatedDate', 'desc');
        System.assert(documentList.size() == 2);
    }

    @IsTest
    private static void testGetFilteredDocument(){
        List<Document__c> documentList = DocumentManagementController.getAllDocuments('Doc 2', 'CreatedDate', 'desc');
        System.assert(documentList.size() == 1);
    }

    @IsTest
    private static void testException(){
        try{
            List<Document__c> documentList = DocumentManagementController.getAllDocuments('Doc 2', '', 'desc');
            System.assert(documentList.size() == 0);
        }catch(Exception e){}
        
    }
}