force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <label>Document Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Version__c.field-meta.xml
<CustomField>
    <fullName>Document_Version__c</fullName>
    <label>Document Version</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DocumentManagementController.cls
public with sharing class DocumentManagementController {

    @AuraEnabled(cacheable=true)
    public static List<Document__c> getAllDocuments(String queryTerm, String fieldName, String sortDirection){
        try{
            String whereClause = '';
            if(String.isNotBlank(queryTerm)){
                queryTerm = '%' + queryTerm + '%';
                whereClause = ' WHERE Name LIKE :queryTerm ';
            }
            String queryStr = 'SELECT Id, Name, Document_Category__c, Document_Version__c FROM Document__c';
            queryStr += whereClause;
            queryStr += ' ORDER BY ' + fieldName + ' ' + sortDirection;
            queryStr += ' LIMIT 50000 ';
            System.debug('queryStr ' + queryStr);
            return (List<Document__c>) Database.query(queryStr);
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}